name: Feature request
description: Suggest an improvement for gPlug Energy Cockpit
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: What problem should the feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
